"""octools: the OpsCogs standard interface for AI agent tools.

One ``OCTool`` descriptor per capability, result envelopes, a conformance
validator, and vendor-neutral converters. The package has no OpsCogs
dependencies so every OpsCogs library can depend on it.
"""

from pathlib import Path

from octools.cells import validate_tabular
from octools.convert import (
    ANTHROPIC_NAME_RE,
    MCP_META_NAMESPACE,
    MCP_NAME_RE,
    to_anthropic_tool,
    to_mcp_tool,
)
from octools.descriptor import (
    ACCESS_FALLBACK,
    ACCESS_KINDS,
    NAME_RE,
    RESULT_KIND_FALLBACK,
    RESULT_KINDS,
    SPEC_VERSION,
    Access,
    OCTool,
    OCToolError,
    ResultKind,
    ToolProvider,
    check_tool_listing,
    merge_providers,
)
from octools.envelopes import (
    COLUMN_KIND_FALLBACK,
    COLUMN_KINDS,
    COLUMN_SCALE_FALLBACK,
    COLUMN_SCALES,
    SENSITIVITY_FALLBACK,
    TABULAR_DEF_NAME,
    VOCABULARY_FALLBACKS,
    ArtifactEnvelope,
    ArtifactRef,
    Cell,
    ColumnKind,
    ColumnScale,
    RecordsEnvelope,
    Sensitivity,
    TabularEnvelope,
    artifact_schema,
    read_envelope,
    records_schema,
    tabular_schema,
)
from octools.findings import Finding
from octools.listing import (
    LISTING_STYLES,
    InputSummary,
    ListingStyle,
    ToolSummary,
    render_listing,
    render_markdown_table,
    summarize_provider,
    summarize_tool,
)
from octools.schema import (
    SCHEMA_DIALECT,
    STRICT_FORMATS,
    STRICT_KEYWORDS,
    STRICT_TYPES,
    NoTitleGenerator,
    close_objects,
    input_schema_for,
    output_schema_for,
    schema_for,
    strict_clean,
    strip_keys,
    strip_titles,
)
from octools.validate import (
    ALIAS_OF_KEY,
    MAX_SENTENCES,
    MIN_SENTENCES,
    SCHEMA_ESCAPE_KEY,
    count_sentences,
    validate_provider,
    validate_tool,
)

_version_file = Path(__file__).parent / "VERSION"
_version = _version_file.read_text() if _version_file.exists() else "0.0.0"
__version__ = _version.rstrip()

__all__ = [
    "ACCESS_FALLBACK",
    "ACCESS_KINDS",
    "ALIAS_OF_KEY",
    "ANTHROPIC_NAME_RE",
    "COLUMN_KINDS",
    "COLUMN_KIND_FALLBACK",
    "COLUMN_SCALES",
    "COLUMN_SCALE_FALLBACK",
    "LISTING_STYLES",
    "MAX_SENTENCES",
    "MCP_META_NAMESPACE",
    "MCP_NAME_RE",
    "MIN_SENTENCES",
    "NAME_RE",
    "RESULT_KINDS",
    "RESULT_KIND_FALLBACK",
    "SCHEMA_DIALECT",
    "SCHEMA_ESCAPE_KEY",
    "SENSITIVITY_FALLBACK",
    "SPEC_VERSION",
    "STRICT_FORMATS",
    "STRICT_KEYWORDS",
    "STRICT_TYPES",
    "TABULAR_DEF_NAME",
    "VOCABULARY_FALLBACKS",
    "Access",
    "ArtifactEnvelope",
    "ArtifactRef",
    "Cell",
    "ColumnKind",
    "ColumnScale",
    "Finding",
    "InputSummary",
    "ListingStyle",
    "NoTitleGenerator",
    "OCTool",
    "OCToolError",
    "RecordsEnvelope",
    "ResultKind",
    "Sensitivity",
    "TabularEnvelope",
    "ToolProvider",
    "ToolSummary",
    "__version__",
    "artifact_schema",
    "check_tool_listing",
    "close_objects",
    "count_sentences",
    "input_schema_for",
    "merge_providers",
    "output_schema_for",
    "read_envelope",
    "records_schema",
    "render_listing",
    "render_markdown_table",
    "schema_for",
    "strict_clean",
    "strip_keys",
    "strip_titles",
    "summarize_provider",
    "summarize_tool",
    "tabular_schema",
    "to_anthropic_tool",
    "to_mcp_tool",
    "validate_provider",
    "validate_tabular",
    "validate_tool",
]
